### ISSUE TITLE
I have a problem : NullPointerException

### ISSUE THREAD

**Issue by Lopeca** [bieliaievays/Tess-two_example#1]
It works until capture the image by my phone, but just next step, it deads with error.
I will capture the details if you need, but not now because I'm far from my computer.
The name of directory to the project is made of only English(*I'm Korean). 
I'm a beginner using android studio(+java) and github, so what I missed can be simple. 
I just know ndk is working :) um.. Do I have to do other thing except 'Usefull info'?

**Comment by ashomokdev** [comment]
Hello. Have you install the app from Google Play Market? Is it works ok? I need more info about the error. Please provide stack trace, screenshots, etc about the error. Thank you in advance.

**Comment by Lopeca** [comment]
I tried the app from Google Play, and introduced to other person. Both we are failed. But one of tries at my home was succeeded. 
![kakaotalk_20160525_161920688](https://cloud.githubusercontent.com/assets/17897555/15531283/87c31a88-2294-11e6-8fa0-6138a7d49a02.jpg)
![kakaotalk_20160525_161921896](https://cloud.githubusercontent.com/assets/17897555/15531282/87c2a080-2294-11e6-9986-5f78aa48cd0e.png)

Don't care about black area. Original one is not shown in recent list. 
The picture with black area is succeeded. 

This is error logs.
well.. How can I send it better,

05-25 16:12:51.230 21625-21625/com.ashomok.tesseractsample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.ashomok.tesseractsample, PID: 21625
                                                                             java.lang.RuntimeException: Unable to resume activity {com.ashomok.tesseractsample/com.ashomok.tesseractsample.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.ashomok.tesseractsample/com.ashomok.tesseractsample.MainActivity}: java.lang.NullPointerException
                                                                                 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2798)
                                                                                 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2827)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:142)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5120)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.ashomok.tesseractsample/com.ashomok.tesseractsample.MainActivity}: java.lang.NullPointerException
                                                                                 at android.app.ActivityThread.deliverResults(ActivityThread.java:3385)
                                                                                 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2785)
                                                                                 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2827) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:142) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:136) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5120) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                                                                                 at dalvik.system.NativeStart.main(Native Method) 
                                                                              Caused by: java.lang.NullPointerException
                                                                                 at com.ashomok.tesseractsample.MainActivity.startOCR(MainActivity.java:164)
                                                                                 at com.ashomok.tesseractsample.MainActivity.onActivityResult(MainActivity.java:83)
                                                                                 at android.app.Activity.dispatchActivityResult(Activity.java:5467)
                                                                                 at android.app.ActivityThread.deliverResults(ActivityThread.java:3381)
                                                                                 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2785) 
                                                                                 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2827) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:142) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:136) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5120) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by ashomokdev** [comment]
Hi again. The source of problem is not the image you provided. I've added unit test to the project and your image was processed ok. I still unable to reproduce the bug. Anyway I was updated onActivityResult method and now it looks safe. You can try to use new version of the src and apk.

**Comment by Lopeca** [comment]
Thanks! It works! This issue can be closed. There is no error.

Well.. Would you try this one?
![kakaotalk_20160530_185529125](https://cloud.githubusercontent.com/assets/17897555/15767739/ae6e1a0a-2985-11e6-852c-220ddc24201a.jpg)
I've made the code for loading a image from gallery and tried with this whole image.
Use kor.traineddata if you need. It shows no result.

**Comment by Lopeca** [comment]
oh, maybe I have to find the part between the point of loading image and starting tesseract
